// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teledocer.Controllers;

namespace Teledocer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Teledocer.Models.Clients", b =>
                {
                    b.Property<int>("Id_clients")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_add");

                    b.Property<DateTime>("Data_reload");

                    b.Property<long>("Inn_kl");

                    b.Property<string>("Name_corp")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.HasKey("Id_clients");

                    b.HasIndex("Type");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Teledocer.Models.founder", b =>
                {
                    b.Property<long>("Inn_uch")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_add");

                    b.Property<DateTime>("Date_reload");

                    b.Property<string>("Fio")
                        .IsRequired();

                    b.Property<int>("Id_founder");

                    b.Property<int>("fff");

                    b.HasKey("Inn_uch");

                    b.HasIndex("Id_founder");

                    b.ToTable("founder");
                });

            modelBuilder.Entity("Teledocer.Models.Types", b =>
                {
                    b.Property<int>("Id_type")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name_of_type")
                        .IsRequired();

                    b.HasKey("Id_type");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("Teledocer.Models.Clients", b =>
                {
                    b.HasOne("Teledocer.Models.Types", "Types")
                        .WithMany("Clientes")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Teledocer.Models.founder", b =>
                {
                    b.HasOne("Teledocer.Models.Clients", "Clients")
                        .WithMany("Founders")
                        .HasForeignKey("Id_founder")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
